
import {Product} from "./types";

export const products: Product[] = [
  // Audio & Sound
  {
    id: '1',
    name: 'Wireless Bluetooth Earbuds',
    price: 79.99,
    image: '/api/placeholder/300/300',
    category: 'audio',
    description: 'Premium wireless earbuds with noise cancellation and 24h battery life',
    inStock: true,
  },
  {
    id: '2',
    name: 'Gaming Headset RGB',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'audio',
    description: 'Professional gaming headset with surround sound and RGB lighting',
    inStock: true,
  },
  {
    id: '3',
    name: 'Bluetooth Portable Speaker',
    price: 49.99,
    image: '/api/placeholder/300/300',
    category: 'audio',
    description: 'Waterproof Bluetooth speaker with 12-hour battery life',
    inStock: true,
  },
  {
    id: '4',
    name: 'Home Theater Soundbar',
    price: 299.99,
    image: '/api/placeholder/300/300',
    category: 'audio',
    description: '3.1 channel soundbar with wireless subwoofer and Dolby Atmos',
    inStock: true,
  },

  // Computers & Laptops
  {
    id: '5',
    name: 'Gaming Laptop RTX 4060',
    price: 1299.99,
    image: '/api/placeholder/300/300',
    category: 'computers',
    description: '15.6" gaming laptop with RTX 4060, 16GB RAM, and 1TB SSD',
    inStock: true,
  },
  {
    id: '6',
    name: 'Business Ultrabook',
    price: 899.99,
    image: '/api/placeholder/300/300',
    category: 'computers',
    description: 'Lightweight 14" ultrabook with Intel i7, 16GB RAM, perfect for professionals',
    inStock: true,
  },
  {
    id: '7',
    name: 'Gaming Desktop PC',
    price: 1899.99,
    image: '/api/placeholder/300/300',
    category: 'computers',
    description: 'High-performance gaming PC with RTX 4070, AMD Ryzen 7, 32GB RAM',
    inStock: true,
  },
  {
    id: '8',
    name: '27" 4K Gaming Monitor',
    price: 399.99,
    image: '/api/placeholder/300/300',
    category: 'computers',
    description: '27" 4K monitor with 144Hz refresh rate and HDR support',
    inStock: true,
  },
  {
    id: '9',
    name: 'Mechanical Gaming Keyboard',
    price: 129.99,
    image: '/api/placeholder/300/300',
    category: 'computers',
    description: 'RGB mechanical keyboard with Cherry MX switches and programmable keys',
    inStock: true,
  },

  // Mobile Devices & Tablets
  {
    id: '10',
    name: 'Smartphone Pro 256GB',
    price: 999.99,
    image: '/api/placeholder/300/300',
    category: 'mobile',
    description: 'Latest flagship smartphone with 256GB storage, triple camera system',
    inStock: true,
  },
  {
    id: '11',
    name: 'Android Tablet 10.1"',
    price: 249.99,
    image: '/api/placeholder/300/300',
    category: 'mobile',
    description: '10.1" Android tablet with 4GB RAM, perfect for entertainment and productivity',
    inStock: true,
  },
  {
    id: '12',
    name: 'Wireless Charging Pad',
    price: 29.99,
    image: '/api/placeholder/300/300',
    category: 'mobile',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices',
    inStock: true,
  },
  {
    id: '13',
    name: 'Power Bank 20000mAh',
    price: 39.99,
    image: '/api/placeholder/300/300',
    category: 'mobile',
    description: 'High-capacity power bank with fast charging and multiple USB ports',
    inStock: true,
  },

  // TV & Entertainment
  {
    id: '14',
    name: '55" 4K Smart TV',
    price: 599.99,
    image: '/api/placeholder/300/300',
    category: 'entertainment',
    description: '55" 4K UHD Smart TV with built-in streaming apps and voice control',
    inStock: true,
  },
  {
    id: '15',
    name: '65" OLED TV',
    price: 1499.99,
    image: '/api/placeholder/300/300',
    category: 'entertainment',
    description: '65" OLED TV with perfect blacks, HDR10+, and premium picture quality',
    inStock: true,
  },
  {
    id: '16',
    name: 'Streaming Media Player',
    price: 49.99,
    image: '/api/placeholder/300/300',
    category: 'entertainment',
    description: '4K streaming device with voice remote and all major apps',
    inStock: true,
  },
  {
    id: '17',
    name: 'PlayStation 5 Console',
    price: 499.99,
    image: '/api/placeholder/300/300',
    category: 'entertainment',
    description: 'Latest PlayStation 5 console with ultra-high speed SSD and DualSense controller',
    inStock: false,
  },

  // Home Appliances
  {
    id: '18',
    name: 'Digital Air Fryer 5.8QT',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'appliances',
    description: 'Digital air fryer with 8 preset programs and easy-to-clean basket',
    inStock: true,
  },
  {
    id: '19',
    name: 'Espresso Coffee Machine',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'appliances',
    description: 'Professional espresso machine with milk frother and programmable settings',
    inStock: true,
  },
  {
    id: '20',
    name: 'Robot Vacuum Cleaner',
    price: 299.99,
    image: '/api/placeholder/300/300',
    category: 'appliances',
    description: 'Smart robot vacuum with mapping, app control, and auto-empty station',
    inStock: true,
  },
  {
    id: '21',
    name: '1000W Microwave Oven',
    price: 129.99,
    image: '/api/placeholder/300/300',
    category: 'appliances',
    description: 'Countertop microwave with sensor cooking and easy-clean interior',
    inStock: true,
  },

  // Smart Home & IoT
  {
    id: '22',
    name: 'Smart WiFi Security Camera',
    price: 79.99,
    image: '/api/placeholder/300/300',
    category: 'smarthome',
    description: '1080p WiFi security camera with night vision and motion detection',
    inStock: true,
  },
  {
    id: '23',
    name: 'Smart Light Bulbs 4-Pack',
    price: 39.99,
    image: '/api/placeholder/300/300',
    category: 'smarthome',
    description: 'Color-changing smart bulbs with voice control and scheduling',
    inStock: true,
  },
  {
    id: '24',
    name: 'Smart Thermostat',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'smarthome',
    description: 'Programmable smart thermostat with energy-saving features and app control',
    inStock: true,
  },
  {
    id: '25',
    name: 'Smart Speaker with Display',
    price: 149.99,
    image: '/api/placeholder/300/300',
    category: 'smarthome',
    description: 'Smart speaker with 8" HD display, voice assistant, and video calling',
    inStock: true,
  },

  // Photography & Video
  {
    id: '26',
    name: 'DSLR Camera 24MP',
    price: 699.99,
    image: '/api/placeholder/300/300',
    category: 'photography',
    description: '24MP DSLR camera with 18-55mm lens, perfect for beginners and enthusiasts',
    inStock: true,
  },
  {
    id: '27',
    name: '4K Action Camera',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'photography',
    description: 'Waterproof 4K action camera with image stabilization and WiFi',
    inStock: true,
  },
  {
    id: '28',
    name: 'Camera Tripod Professional',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'photography',
    description: 'Professional tripod with fluid head and quick-release plate',
    inStock: true,
  },
  {
    id: '29',
    name: 'Drone with 4K Camera',
    price: 899.99,
    image: '/api/placeholder/300/300',
    category: 'photography',
    description: 'Professional drone with 4K camera, GPS, and 30-minute flight time',
    inStock: true,
  },

  // Wearable Technology
  {
    id: '30',
    name: 'Fitness Smartwatch',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'wearables',
    description: 'Fitness smartwatch with heart rate monitor, GPS, and 7-day battery',
    inStock: true,
  },
  {
    id: '31',
    name: 'Fitness Tracker Band',
    price: 59.99,
    image: '/api/placeholder/300/300',
    category: 'wearables',
    description: 'Lightweight fitness tracker with sleep monitoring and water resistance',
    inStock: true,
  },
  {
    id: '32',
    name: 'Smart Health Scale',
    price: 49.99,
    image: '/api/placeholder/300/300',
    category: 'wearables',
    description: 'Smart scale that tracks weight, BMI, and body composition via app',
    inStock: true,
  },

  // Gaming & Electronics
  {
    id: '33',
    name: 'Graphics Card RTX 4070',
    price: 899.99,
    image: '/api/placeholder/300/300',
    category: 'gaming',
    description: 'High-performance graphics card for 4K gaming and content creation',
    inStock: true,
  },
  {
    id: '34',
    name: 'Gaming Mouse RGB',
    price: 79.99,
    image: '/api/placeholder/300/300',
    category: 'gaming',
    description: 'High-precision gaming mouse with 16000 DPI and customizable RGB',
    inStock: true,
  },
  {
    id: '35',
    name: 'VR Headset',
    price: 399.99,
    image: '/api/placeholder/300/300',
    category: 'gaming',
    description: 'All-in-one VR headset with inside-out tracking and wireless freedom',
    inStock: true,
  },
  {
    id: '36',
    name: 'Wireless Gaming Controller',
    price: 69.99,
    image: '/api/placeholder/300/300',
    category: 'gaming',
    description: 'Wireless controller with haptic feedback and 20-hour battery life',
    inStock: true,
  },

  // Cables & Accessories
  {
    id: '37',
    name: 'USB-C Cable 6ft 3-Pack',
    price: 19.99,
    image: '/api/placeholder/300/300',
    category: 'accessories',
    description: 'Fast charging USB-C cables with data transfer support, pack of 3',
    inStock: true,
  },
  {
    id: '38',
    name: 'External Hard Drive 2TB',
    price: 79.99,
    image: '/api/placeholder/300/300',
    category: 'accessories',
    description: 'Portable 2TB external hard drive with USB 3.0 for backup and storage',
    inStock: true,
  },
  {
    id: '39',
    name: 'Multi-Device Charging Station',
    price: 59.99,
    image: '/api/placeholder/300/300',
    category: 'accessories',
    description: '6-port charging station with wireless charging pad and cable management',
    inStock: true,
  },
  {
    id: '40',
    name: 'USB Flash Drive 128GB',
    price: 24.99,
    image: '/api/placeholder/300/300',
    category: 'accessories',
    description: 'High-speed 128GB USB 3.1 flash drive with compact design',
    inStock: true,
  },
  // Drones & RC
  {
    id: '41',
    name: 'Professional Drone 4K Camera',
    price: 1299.99,
    image: '/api/placeholder/300/300',
    category: 'drones',
    description: 'Professional drone with 4K gimbal camera, 35-minute flight time, and GPS',
    inStock: true,
  },
  {
    id: '42',
    name: 'Racing Drone FPV',
    price: 399.99,
    image: '/api/placeholder/300/300',
    category: 'drones',
    description: 'High-speed FPV racing drone with HD camera and racing goggles included',
    inStock: true,
  },
  {
    id: '43',
    name: 'RC Car Off-Road 4WD',
    price: 159.99,
    image: '/api/placeholder/300/300',
    category: 'drones',
    description: 'Remote control off-road car with 4WD, waterproof design, and 2.4GHz control',
    inStock: true,
  },

  // Outdoor & Garden
  {
    id: '44',
    name: 'Robotic Lawn Mower',
    price: 899.99,
    image: '/api/placeholder/300/300',
    category: 'outdoor',
    description: 'Smart robotic lawn mower with app control, anti-theft system, and weather sensor',
    inStock: true,
  },
  {
    id: '45',
    name: 'Electric Leaf Blower',
    price: 129.99,
    image: '/api/placeholder/300/300',
    category: 'outdoor',
    description: 'Cordless leaf blower with variable speed control and 40V battery',
    inStock: true,
  },
  {
    id: '46',
    name: 'Pressure Washer Electric',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'outdoor',
    description: '2000 PSI electric pressure washer with multiple nozzles and detergent tank',
    inStock: true,
  },
  {
    id: '47',
    name: 'Hedge Trimmer Cordless',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'outdoor',
    description: '20V cordless hedge trimmer with 22-inch blade and rotating handle',
    inStock: true,
  },

  // Toys & Kids Electronics
  {
    id: '48',
    name: 'Kids Electric Car 12V',
    price: 299.99,
    image: '/api/placeholder/300/300',
    category: 'toys',
    description: '12V electric ride-on car with remote control, LED lights, and MP3 player',
    inStock: true,
  },
  {
    id: '49',
    name: 'RC Racing Car High Speed',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'toys',
    description: 'High-speed RC car with 2.4GHz remote, rechargeable battery, and LED lights',
    inStock: true,
  },
  {
    id: '50',
    name: 'Electric Scooter Kids',
    price: 149.99,
    image: '/api/placeholder/300/300',
    category: 'toys',
    description: 'Electric scooter for kids with LED wheels, adjustable height, and safety features',
    inStock: true,
  },
  {
    id: '51',
    name: 'Educational Robot Kit',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'toys',
    description: 'STEM educational robot kit with programming capabilities and sensors',
    inStock: true,
  },

  // Tools & Equipment
  {
    id: '52',
    name: 'Cordless Drill Set 20V',
    price: 149.99,
    image: '/api/placeholder/300/300',
    category: 'tools',
    description: '20V cordless drill with 2 batteries, charger, and 30-piece accessory kit',
    inStock: true,
  },
  {
    id: '53',
    name: 'Circular Saw Electric',
    price: 179.99,
    image: '/api/placeholder/300/300',
    category: 'tools',
    description: '15-amp circular saw with laser guide and carbide-tipped blade',
    inStock: true,
  },
  {
    id: '54',
    name: 'Tool Set 100 Piece',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'tools',
    description: 'Complete 100-piece tool set with carrying case and lifetime warranty',
    inStock: true,
  },
  {
    id: '55',
    name: 'Work Light LED Rechargeable',
    price: 39.99,
    image: '/api/placeholder/300/300',
    category: 'tools',
    description: 'Portable LED work light with magnetic base and USB charging',
    inStock: true,
  },

  // Fitness & Health
  {
    id: '56',
    name: 'Folding Treadmill',
    price: 599.99,
    image: '/api/placeholder/300/300',
    category: 'fitness',
    description: 'Space-saving folding treadmill with LCD display and 12 preset programs',
    inStock: true,
  },
  {
    id: '57',
    name: 'Exercise Bike Stationary',
    price: 399.99,
    image: '/api/placeholder/300/300',
    category: 'fitness',
    description: 'Magnetic resistance exercise bike with heart rate monitor and tablet holder',
    inStock: true,
  },
  {
    id: '58',
    name: 'Massage Gun Percussion',
    price: 129.99,
    image: '/api/placeholder/300/300',
    category: 'fitness',
    description: 'Deep tissue massage gun with 6 heads and adjustable speed settings',
    inStock: true,
  },

  // Automotive Electronics
  {
    id: '59',
    name: 'Dash Cam 4K Front/Rear',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'automotive',
    description: '4K dash cam with front and rear cameras, night vision, and GPS tracking',
    inStock: true,
  },
  {
    id: '60',
    name: 'Car GPS Navigation',
    price: 149.99,
    image: '/api/placeholder/300/300',
    category: 'automotive',
    description: '7-inch GPS navigator with lifetime map updates and voice commands',
    inStock: true,
  },
  {
    id: '61',
    name: 'Car Stereo Bluetooth',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'automotive',
    description: 'Bluetooth car stereo with USB, AUX, and hands-free calling',
    inStock: true,
  },

  // Office Electronics
  {
    id: '62',
    name: 'All-in-One Printer',
    price: 179.99,
    image: '/api/placeholder/300/300',
    category: 'office',
    description: 'Wireless all-in-one printer with scan, copy, and fax capabilities',
    inStock: true,
  },
  {
    id: '63',
    name: 'Portable Projector 4K',
    price: 299.99,
    image: '/api/placeholder/300/300',
    category: 'office',
    description: 'Compact 4K projector with WiFi, Bluetooth, and built-in speaker',
    inStock: true,
  },
  {
    id: '64',
    name: 'Paper Shredder Cross-Cut',
    price: 79.99,
    image: '/api/placeholder/300/300',
    category: 'office',
    description: '12-sheet cross-cut shredder with 5-gallon basket and auto-reverse',
    inStock: true,
  },

  // Power & Energy
  {
    id: '65',
    name: 'Portable Power Station',
    price: 699.99,
    image: '/api/placeholder/300/300',
    category: 'power',
    description: '500Wh portable power station with AC outlets, USB ports, and solar charging',
    inStock: true,
  },
  {
    id: '66',
    name: 'Solar Panel Kit 100W',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'power',
    description: '100W solar panel kit with charge controller and mounting hardware',
    inStock: true,
  },
  {
    id: '67',
    name: 'UPS Battery Backup',
    price: 149.99,
    image: '/api/placeholder/300/300',
    category: 'power',
    description: 'Uninterruptible power supply with surge protection and LCD display',
    inStock: true,
  },

  // Climate Control
  {
    id: '68',
    name: 'Air Purifier HEPA',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'climate',
    description: 'HEPA air purifier with UV-C light and smart air quality sensor',
    inStock: true,
  },
  {
    id: '69',
    name: 'Ultrasonic Humidifier',
    price: 69.99,
    image: '/api/placeholder/300/300',
    category: 'climate',
    description: 'Ultrasonic humidifier with essential oil diffuser and remote control',
    inStock: true,
  },
  {
    id: '70',
    name: 'Tower Fan Oscillating',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'climate',
    description: '42-inch tower fan with remote control, timer, and 3 speed settings',
    inStock: true,
  },

  // Security & Safety
  {
    id: '71',
    name: 'Smart Door Lock Keyless',
    price: 179.99,
    image: '/api/placeholder/300/300',
    category: 'security',
    description: 'Keyless smart lock with fingerprint, keypad, and smartphone access',
    inStock: true,
  },
  {
    id: '72',
    name: 'Home Security System',
    price: 299.99,
    image: '/api/placeholder/300/300',
    category: 'security',
    description: 'Complete home security system with sensors, cameras, and mobile alerts',
    inStock: true,
  },
  {
    id: '73',
    name: 'Smoke Detector Smart',
    price: 49.99,
    image: '/api/placeholder/300/300',
    category: 'security',
    description: 'Smart smoke detector with smartphone alerts and voice announcements',
    inStock: true,
  },

  // Networking & WiFi
  {
    id: '74',
    name: 'WiFi 6 Router Mesh',
    price: 249.99,
    image: '/api/placeholder/300/300',
    category: 'networking',
    description: 'WiFi 6 mesh router system with coverage up to 6000 sq ft',
    inStock: true,
  },
  {
    id: '75',
    name: 'WiFi Extender AC1900',
    price: 79.99,
    image: '/api/placeholder/300/300',
    category: 'networking',
    description: 'AC1900 WiFi range extender with dual-band and gigabit ethernet port',
    inStock: true,
  },
  {
    id: '76',
    name: 'Network Switch 8-Port',
    price: 39.99,
    image: '/api/placeholder/300/300',
    category: 'networking',
    description: '8-port gigabit network switch with plug-and-play setup',
    inStock: true,
  },

  // Musical Electronics
  {
    id: '77',
    name: 'Electric Guitar Beginner',
    price: 199.99,
    image: '/api/placeholder/300/300',
    category: 'musical',
    description: 'Electric guitar starter pack with amplifier, cables, and accessories',
    inStock: true,
  },
  {
    id: '78',
    name: 'Digital Piano 88-Key',
    price: 599.99,
    image: '/api/placeholder/300/300',
    category: 'musical',
    description: '88-key digital piano with weighted keys and built-in speakers',
    inStock: true,
  },
  {
    id: '79',
    name: 'Audio Mixer 4-Channel',
    price: 129.99,
    image: '/api/placeholder/300/300',
    category: 'musical',
    description: '4-channel audio mixer with USB interface and phantom power',
    inStock: true,
  },

  // Electronics Components
  {
    id: '80',
    name: 'Arduino Starter Kit',
    price: 89.99,
    image: '/api/placeholder/300/300',
    category: 'components',
    description: 'Complete Arduino starter kit with sensors, LEDs, and project guide',
    inStock: true,
  },

];

export const categories = [
  { slug: 'audio', name: 'Audio & Sound', icon: '🎧' },
  { slug: 'computers', name: 'Computers & Laptops', icon: '💻' },
  { slug: 'mobile', name: 'Mobile & Tablets', icon: '📱' },
  { slug: 'entertainment', name: 'TV & Entertainment', icon: '📺' },
  { slug: 'appliances', name: 'Home Appliances', icon: '🏠' },
  { slug: 'smarthome', name: 'Smart Home & IoT', icon: '🏡' },
  { slug: 'photography', name: 'Photography & Video', icon: '📷' },
  { slug: 'wearables', name: 'Wearable Technology', icon: '⌚' },
  { slug: 'gaming', name: 'Gaming & Electronics', icon: '🎮' },
  { slug: 'accessories', name: 'Cables & Accessories', icon: '🔌' },
  { slug: 'drones', name: 'Drones & RC', icon: '🚁' },
  { slug: 'outdoor', name: 'Outdoor & Garden', icon: '🌿' },
  { slug: 'toys', name: 'Toys & Kids Electronics', icon: '🧸' },
  { slug: 'tools', name: 'Tools & Equipment', icon: '🔧' },
  { slug: 'fitness', name: 'Fitness & Health', icon: '🏋️' },
  { slug: 'automotive', name: 'Automotive Electronics', icon: '🚗' },
  { slug: 'office', name: 'Office Electronics', icon: '🏢' },
  { slug: 'power', name: 'Power & Energy', icon: '🔋' },
  { slug: 'climate', name: 'Climate Control', icon: '🌡️' },
  { slug: 'security', name: 'Security & Safety', icon: '🔒' },
  { slug: 'networking', name: 'Networking & WiFi', icon: '📡' },
  { slug: 'musical', name: 'Musical Electronics', icon: '🎵' },
  { slug: 'components', name: 'Electronics Components', icon: '⚡' },

];

export function getProductsByCategory(category: string) {
  return products.filter(product => product.category === category);
}

export function getProductById(id: string) {
  return products.find(product => product.id === id);
}